### ISSUE TITLE
Backslashes are written to "import" statements on Windows

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#293]
*CUBA Platform version: 7.2.7
CUBA Studio plugin version: 15.0.SNAPSHOT2434-193
IntelliJ version: IntelliJ IDEA 2020.1.2 (Community Edition)
Frontend gen version 3.1.0
Windows 10*

Probably broken in #268
1) Create a project
2) Create an entity
3) Create front module in Studio 
4) Then create an entity-management component using Studio or CLI
```
cd modules\front
gen-cuba-front react-typescript:entity-management -s ../../ -d src/app/mainentity

```
5) Start the application server
**AR:** Compilation failed
```
> Task :app-front:buildFrontend

> fesmktst@0.1.0 build D:\projects\2020.08.04\fesmktst\modules\front
> react-scripts build

Creating an optimized production build...
Failed to compile.

.\src\app\mainentity1\Meedit.tsx
Cannot find module: '....cuba/entities/fesmktst_MainEntity'. Make sure this package is installed.

You can install this package by running: npm install ....cuba/entities/fesmktst_MainEntity.
```
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/89e62684-e261-4e52-966d-2500d881759f)
